# Generated by Django 3.2.13 on 2022-06-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('description', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Gasto',
                'verbose_name_plural': 'Categoria de Gastos',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date', '-value', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Limite Mensal',
                'verbose_name_plural': 'Limites Mensais',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('description', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Categoria de Pagamento',
                'verbose_name_plural': 'Categoria de Pagamentos',
                'ordering': ['description'],
            },
        ),
        migrations.AddConstraint(
            model_name='limit',
            constraint=models.UniqueConstraint(fields=('month', 'year'), name='unique_expense_limit_by_month_year'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='related_category', to='expenses.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='related_payment', to='expenses.payment'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('category', 'payment', 'date', 'description'), name='unique_expense'),
        ),
    ]
